language: c

compiler:
 - gcc
 - clang

env:
  - BUILD=autotools
  - BUILD=cmake

script:
  - if [ $BUILD == "autotools" ]; then ./autogen.sh && ./configure && make && make check; fi
  - if [ $BUILD == "cmake" ]; then cmake . && make && make test; fi

before_install:
  - sudo add-apt-repository --yes ppa:czchen/travis-ci # For cmake 2.8.9
  - sudo apt-get update -qq
  - sudo apt-get install -qq texinfo cmake valgrind

notifications:
 email:
  recipients:
   - chewing-devel@googlegroups.com
