name: vulcan

on:
    workflow_run:
        workflows: [regression test]
        types: [completed]

jobs:
    auto-repair:
        runs-on: self-hosted
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: check ENV
              run: export
              shell: bash
            - name: run vulcan action
              uses: Suresoft-GLaDOS/vulcan-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
