name: vulcan

on:
    workflow_run:
        workflows: [regression test]
        types: [completed]

jobs:
    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - name: run vulcan action
              uses: Suresoft-GLaDOS/vulcan-action@main
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                path: vulcan_target