name: regression test

on:
    # push:
    workflow_dispatch:
            
jobs:
    checkout:
        runs-on: self-hosted
        steps:
            - name: checkout source code
              uses: actions/checkout@v2
    build:
        needs: checkout
        runs-on: self-hosted
        steps:
            - name: run build
              run: |
                cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build -G Ninja  
                cmake --build build --target clean
                cmake --build build --target all --parallel 10
    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: run test
              run: |
                    chmod -R 777 tools;tools/tiffcrop .dpp/CVE-2016-5321.tif /tmp/tmpout.tif
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 1)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 2)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 3)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 4)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 5)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 6)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 7)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 10)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 11)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 12)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 13)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 14)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 15)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 16)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 17)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 18)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 19)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 20)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 21)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 22)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 23)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 24)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 25)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 26)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 27)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 28)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 29)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 30)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 31)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 32)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 33)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 34)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 35)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 36)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 37)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 38)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 39)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 40)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 41)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 42)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 43)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 44)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 45)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 46)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 47)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 48)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 49)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 50)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 51)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 52)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 53)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 54)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 55)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 56)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 57)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 58)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 59)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 60)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 61)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 62)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 63)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 64)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 65)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 66)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 67)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 68)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 69)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 70)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 71)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 72)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 73)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 74)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 75)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 76)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 77)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 78)
                    chmod -R 777 .;cd test;make check-TESTS --no-print-directory TESTS=$(chmod -R 777 .;cd test;make print-TESTS | cut -d ' ' -f 79)
