name: regression test

on:
    # push:
    workflow_dispatch:
            
jobs:
    checkout:
        runs-on: self-hosted
        steps:
            - name: checkout source code
              uses: actions/checkout@v2
    build:
        needs: checkout
        runs-on: self-hosted
        steps:
            - name: run build
              run: |
                rm -rf build
                cmake -DCMAKE_BUILD_TYPE=Debug -S . -B build -G Ninja  
                cmake --build build --target clean
                cmake --build build --target all --parallel 10
    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: run test
              run: |
                    declare -x ISOLATED="1"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="2"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="3"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="4"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="5"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="6"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="7"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="8"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="9"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="10"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="11"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="12"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="13"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="14"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="15"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="16"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="17"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="18"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="19"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="20"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build
                    declare -x ISOLATED="21"; ctest --output-on-failure --tests-regex test-bopomofo --test-dir build