name: regression test

on:
    # push:
    workflow_dispatch:
            
jobs:
    checkout:
        runs-on: self-hosted
        steps:
            - name: checkout source code
              uses: actions/checkout@v2
    build:
        needs: checkout
        runs-on: self-hosted
        steps:
            - name: run build
              run: |
                make clean
                make
    test:
        needs: build
        runs-on: self-hosted
        steps:
            - name: run test
              run: |
                ./test 5 0
                ./test 5 1
                ./test 5 2
                ./test 5 3
                ./test 6 0
                ./test 6 1
                ./test 6 2
                ./test 6 3
                ./test 6 4
                ./test 6 5
                ./test 6 6
                ./test 6 7
#                ./test 7 0
#                ./test 7 1
#                ./test 7 2
#                ./test 7 3
#                ./test 7 4
#                ./test 7 5
#                ./test 7 6
#                ./test 7 7
